account_id = "7a7bc5a554ebb237cf4f53f918ddc6fa"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "0b3cfcab69c84977a4f0c823dc4c4338" }, ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "0b3cfcab69c84977a4f0c823dc4c4338" }, ]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/2_*_*_*_*
  # Check monitors
  "*/2 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  "*/10 * * * *",
]
