account_id = "814783760629c5adc3ff6fa69916fd8b"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "83944df5b99b43a5804ba0902579194f" }, ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "83944df5b99b43a5804ba0902579194f" }, ]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/2_*_*_*_*
  # Check monitors
  "*/30 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  "0 * * * *",
]
